[[proxy]]
name = "http"
listen = "0.0.0.0:89"

[[container]]
replicas = 1
name = "nginx"
image = "nginx:latest"
container_port = 80
health_checks = ["http"]
proxies = ["http"]

[[container]]
replicas = 2
name = "apache"
image = "httpd:2.4"
container_port = 80
health_checks = ["http"]
proxies = ["http"]

[[health_check]]
name = "http"
check = "http"
url = "http://127.0.0.1:{{container.port_dynamic_host}}"
timeout_ms = 1000