[package]
name = "easyact"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.*", features=["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "*"
futures = "0.3"
tokio-util = "0.7.*"
async-trait = "0.1.*"
pin-project-lite = "0.2.*"
console-subscriber = "*"